import { chromium } from 'playwright-core';
const [,, url, out, w = 1280, h = 800, wait = 3000, full = ''] = process.argv;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: +w, height: +h } });
const logs = [];
page.on('pageerror', e => logs.push('ERR ' + e.message));
await page.goto(url).catch(e => logs.push(e.message));
await page.waitForTimeout(+wait);
await page.screenshot({ path: out, fullPage: !!full });
const txt = await page.evaluate(() => document.body.innerText.slice(0, 3000));
console.log(txt); console.log(logs.slice(0, 5).join('\n'));
await browser.close();
