// Las ventanas del juego que miden las auditorías de interfaz (popups-medir, ux-medir): cómo se abre cada una con
// textos de ejemplo largos, sobre un pueblo cargado. Uso: await cargarModulos(page); luego eval(casos(touch)[k]).
export async function cargarModulos(p) {
  await p.evaluate(async () => { window.__mods = { MG: await import('/src/ui/minigames.js'), FI: await import('/src/ui/ficha.js'), FH: await import('/src/futbol/hud.js'), PH: await import('/src/pelota/hud.js'), PM: await import('/src/pelota/match.js'), PR: await import('/src/pelota/rules.js'), LG: await import('/src/futbol/liga.js'), TO: await import('/src/game/torneo.js'), CL: await import('/src/futbol/clubs.js'), RU: await import('/src/futbol/rules.js'), ES: await import('/src/ui/escudo.js'), CH: await import('/src/ui/champion.js'), AR: await import('/src/data/armas-navarra.js') }; window.__club = Object.keys(window.__mods.CL.CLUBS)[0]; });
}
export const casos = (touch) => ({
  'dialogo': `G.ui.dialog([{ name: 'Ane', text: 'Hola, ¿me ayudas a llevar el queso a la quesería? Está al otro lado del puente, junto a la iglesia.', choices: ['Sí, vamos', 'Ahora no puedo'] }])`,
  'premio': `G.ui.reward({ icon: 'star', title: 'Nueva insignia', text: 'Has conocido a todos los oficios del pueblo y aprendido cómo se hacía el queso.' })`,
  'cuaderno': `G.ui.openBook('misiones')`, 'mapa': `G.ui.openMap()`, 'pausa': `G.ui.openMenu()`,
  'mochila': `G.mochila?.open()`, 'tienda': `G.tienda?.open()`,
  'info': `M.MG.infoCard(G.ui, { icon: 'church', kicker: 'Arte gótico', title: 'Iglesia de San Pedro', text: 'Iglesia gótica del siglo XVI con contrafuertes, una gran torre y un rosetón sobre la portada. Dentro está el viejo órgano del monasterio.', badge: 'Nueva carta', button: 'Seguir (1/3)' })`,
  'mision-cumplida': `M.MG.missionComplete(G.ui, { title: 'Del rebaño al queso', text: 'Has ordenado bien todos los pasos y Ane ya tiene su queso.', xp: 40, card: 'Queso Idiazabal', progress: { done: 2, total: 5, name: 'Lumbier' } })`,
  'elegir': `M.MG.choiceGame(G.ui, { title: 'La quesería', q: '¿Qué se añade a la leche caliente para que cuaje?', options: ['Cuajo', 'Azúcar', 'Harina de maíz'], answer: 0, why: 'El cuajo separa la leche en cuajada y suero.' })`,
  'ordenar': `M.MG.sequenceGame(G.ui, { title: 'Del maíz a la harina', hint: 'Toca los pasos en el orden correcto', steps: ['Recoger las mazorcas', 'Desgranar el maíz', 'Secar el grano', 'Moler en el molino', 'Cerner la harina'] })`,
  'ficha': `M.FI.showFicha(M.FI.allFichas ? (M.FI.allFichas('fauna')[0].type + ':' + M.FI.allFichas('fauna')[0].id) : 'fauna:quebrantahuesos', { ui: G.ui, badge: 'Nueva carta', button: 'Seguir' })`,
  'pelota-inicio': `(() => { const m = Object.create(M.PM.PelotaMatch.prototype), root = document.createElement('div'); root.className = 'pm-test'; document.body.appendChild(root); Object.assign(m, { lang: 'es', txt: M.PR.TEXT.es, names: { you: 'Ane', rival: 'Mikel Etxeberria' }, touch: ${touch}, o: {}, level: 'normal', game: { mode: 'match', target: 7 }, audio: { ensure() {}, whistle() {}, crowd() {} } }); m.hud = new M.PH.PelotaHud(root, m.txt, m.names, ${touch}); m.intro(); })()`,
  'pelota-final': `(() => { const m = Object.create(M.PM.PelotaMatch.prototype), root = document.createElement('div'); root.className = 'pm-test'; document.body.appendChild(root); Object.assign(m, { lang: 'es', txt: M.PR.TEXT.es, names: { you: 'Ane', rival: 'Mikel Etxeberria' }, touch: ${touch}, o: {}, level: 'normal', game: { mode: 'match', target: 7 }, audio: { ensure() {}, whistle() {}, crowd() {} } }); m.hud = new M.PH.PelotaHud(root, m.txt, m.names, ${touch}); m.endPanel({ win: true, score: { you: 7, rival: 5 }, best: 0 }); })()`,
  'pelota-salir': `(() => { const m = Object.create(M.PM.PelotaMatch.prototype), root = document.createElement('div'); root.className = 'pm-test'; document.body.appendChild(root); Object.assign(m, { lang: 'es', txt: M.PR.TEXT.es, names: { you: 'Ane', rival: 'Mikel Etxeberria' }, touch: ${touch}, o: {}, level: 'normal', game: { mode: 'match', target: 7 }, audio: { ensure() {}, whistle() {}, crowd() {} } }); m.hud = new M.PH.PelotaHud(root, m.txt, m.names, ${touch}); m.confirmExit(); })()`,
  'futbol-menu': `M.FH.menuPanel({ title: 'El Sadar', sub: 'Pamplona / Iruña', modes: [['match', 'Partido'], ['penalties', 'Penaltis'], ['reto', 'Retos']], rivals: [['visitante', 'Visitante'], ['tudela', 'CD Tudelano']], values: { mode: 'match', rival: 'visitante', level: 'normal', duration: 3, assist: true, sistema: '4-4-2', sistemas: ['4-4-2', '4-3-3', '4-2-3-1', '5-3-2', '3-5-2'] } })`,
  'futbol-tactica': `(() => { const h = window.__fh = new M.FH.FutbolHud({ touch: ${touch}, home: { name: 'Club Atlético Osasuna', short: 'OSA', shirt: '#d00' }, away: { name: 'Club Deportivo Tudelano', short: 'TUD', shirt: '#06c' } }); h.tactic({ sistemas: M.RU.SISTEMAS, actual: '4-3-3', pick: () => {} }); })()`,
  'escudo-pueblo': `M.ES.readTownArms(G.ui, M.AR.ARMAS.find(a => a.id === 'baztan') || M.AR.ARMAS[0], { town: 'Elizondo', isNew: true })`,
  'campeon': `M.CH.showChampion({ kind: 'pelota', kicker: 'Torneo de mano · Baztan-Bidasoa', title: '¡Txapeldun!', name: 'Ane', sub: 'La txapela de Baztan-Bidasoa es tuya. Zorionak!', score: 'Final · 7 – 5', button: 'Ponerme la txapela' })`,
  'futbol-pausa': `(() => { const h = window.__fh = new M.FH.FutbolHud({ touch: ${touch}, home: { name: 'Club Atlético Osasuna', short: 'OSA', shirt: '#d00' }, away: { name: 'Club Deportivo Tudelano', short: 'TUD', shirt: '#06c' } }); h.pause(); })()`,
  'futbol-controles': `(() => { const h = window.__fh = new M.FH.FutbolHud({ touch: ${touch}, home: { name: 'Club Atlético Osasuna', short: 'OSA', shirt: '#d00' }, away: { name: 'Club Deportivo Tudelano', short: 'TUD', shirt: '#06c' } }); h.controls(); })()`,
  'futbol-final': `(() => { const h = window.__fh = new M.FH.FutbolHud({ touch: ${touch}, home: { name: 'Club Atlético Osasuna', short: 'OSA', shirt: '#d00' }, away: { name: 'Club Deportivo Tudelano', short: 'TUD', shirt: '#06c' } }); h.end({ title: '¡Victoria!', sub: 'Final del partido', score: '3 – 2', rows: [['3', 'Goles', '2'], ['9 (5)', 'Tiros (a puerta)', '7 (3)'], ['58 %', 'Posesión', '42 %'], ['31', 'Pases buenos', '24'], ['6', 'Robos', '4'], ['3', 'Paradas', '6'], ['5', 'Faltas', '8'], ['1', 'Amarillas', '2'], ['0', 'Rojas', '1']], again: 'Revancha', exit: 'Salir', fact: 'La alcachofa de Tudela y el espárrago de Navarra tienen Indicación Geográfica Protegida.' }); })()`,
  'futbol-info': `(() => { const h = window.__fh = new M.FH.FutbolHud({ touch: ${touch}, home: { name: 'Club Atlético Osasuna', short: 'OSA', shirt: '#d00' }, away: { name: 'Club Deportivo Tudelano', short: 'TUD', shirt: '#06c' } }); h.info({ kicker: 'Reto', title: 'Conducción entre conos', text: 'Lleva el balón pegado al pie entre los conos sin tocarlos. Cuanto más rápido, más puntos.', button: 'Empezar' }); })()`,
  'liga-club': `(() => { window.__fh?.dispose(); M.LG.clubPick(); })()`,
  'liga-menu': `(() => { document.querySelectorAll('.lg-root').forEach(x => x.remove()); M.LG.clubPanel(window.__club, [['liga', 'Liga Navarra · jornada 1', 'Fútbol 11 contra los clubes de tu grupo'], ['amistoso', 'Amistoso', 'Contra cualquier club de Navarra'], ['sadar', 'El Sadar', 'Fútbol 11 en el estadio de Iruña'], ['sala', 'Fútbol sala', '5 contra 5 en la pista del pueblo'], ['club', 'Cambiar de club', 'Osasuna'], ['exit', 'Salir', '']], 'Campeonato de fútbol'); })()`,
  'liga-rival': `(() => { document.querySelectorAll('.lg-root').forEach(x => x.remove()); M.LG.rivalPanel(window.__club); })()`,
  'liga-tabla': `(() => { document.querySelectorAll('.lg-root').forEach(x => x.remove()); M.LG.ligaPanel(M.LG.season(window.__club)); })()`,
  'pelota-menu': `(() => { document.querySelectorAll('.lg-root').forEach(x => x.remove()); const g = window.__game, T = M.TO.torneo({ name: 'Ane', town: 'Lumbier' }, { comarca: g.def.comarca, comarcaName: 'la comarca', towns: g.comarcaVenues() }); M.TO.pelotaMenu(T, 'Lumbier'); })()`,
  'torneo': `(() => { document.querySelectorAll('.lg-root,.tn-root').forEach(x => x.remove()); const g = window.__game, T = M.TO.torneo({ name: 'Ane', town: 'Lumbier' }, { comarca: g.def.comarca, comarcaName: 'la comarca', towns: g.comarcaVenues() }); M.TO.torneoPanel(T, 'Lumbier'); })()`,
});
